openapi: "3.0.2"
info:
  title: Classics Proxy API
  version: "1.0"
servers:
  - url: http://localhost:5000
paths:
  /corpora/itkc:
    get:
      operationId: itkc_corpora
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  series:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
          links:
            ListSeries:
              operationId: itkc_series
              parameters:
                seriesId: "$response.body#/series/id"
  /corpora/itkc/{seriesId}:
    get:
      operationId: itkc_series
      parameters:
        - name: "seriesId"
          in: "path"
          schema:
            type: "string"
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  collections:
                    type: array
                    items:
                      type: object
                      properties:
                        authors:
                          type: string
                        data_id:
                          type: string
                        title:
                          type: string
                        zn_title:
                          type: string
  /corpora/itkc/{seriesId}/meta/{dataId}:
    get:
      operationId: itkc_meta
      parameters:
        - name: "seriesId"
          in: "path"
          schema:
            type: "string"
          required: true
        - name: "dataId"
          in: "path"
          schema:
            type: "string"
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  volumes:
                    $ref: "#/components/schemas/Volumes"
  /corpora/itkc/{seriesId}/all_text_meta/{dataId}:
    get:
      operationId: itkc_all_text_meta
      parameters:
        - name: "seriesId"
          in: "path"
          schema:
            type: "string"
          required: true
        - name: "dataId"
          in: "path"
          schema:
            type: "string"
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  volumes:
                    $ref: "#/components/schemas/Volumes"
  /corpora/itkc/{seriesId}/text/{dataId}:
    get:
      operationId: itkc_text
      parameters:
        - name: "seriesId"
          in: "path"
          schema:
            type: "string"
          required: true
        - name: "dataId"
          in: "path"
          schema:
            type: "string"
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                  zn_text:
                    type: string
                  title:
                    type: string
                  zn_title:
                    type: string

components:
  schemas:
    Volumes:
      type: array
      items:
        type: object
        properties:
          title:
            type: string
          data_id:
            type: string
          is_text:
            type: boolean
